### ISSUE TITLE
Upgrade to sentence-transformers v.0.4.1.2

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [MartinoMensio/spacy-sentence-bert#1]
Hi @MartinoMensio,

Would it be possible to upgrade to the latest version of the UKPLab sentence transformer library (https://github.com/UKPLab/sentence-transformers), since I am interested in using a particular multilingual transformer model `stsb-xlm-r-multilingual` (https://www.sbert.net/docs/pretrained_models.html#multi-lingual-models) ?

Thanks !

**Comment by MartinoMensio** [comment]
Hi @Matthieu-Tinycoaching,
Yes sure I will update it soon.

Best,
Martino

**Comment by MartinoMensio** [comment]
Hi @Matthieu-Tinycoaching,

With the latest release, you can use the model you are interested in, and in general any models that are allowed by UKPLab sentence transformer library.

## Option A: installing the model standalone package:
```bash
pip install https://github.com/MartinoMensio/spacy-sentence-bert/releases/download/v0.1.2/xx_stsb_xlm_r_multilingual-0.1.2.tar.gz#xx_stsb_xlm_r_multilingual-0.1.2
```
Then just use SpaCy `load` API:

```python
import spacy
nlp = spacy.load('xx_stsb_xlm_r_multilingual')
```

## Option B: Without language standalone package

With this option you can load any of the models supported by the [sentence-bert library](https://github.com/UKPLab/sentence-transformers)

```bash
pip install spacy-sentence-bert==0.1.2
```

Then in python:
```python
import spacy
# load any model you want
nlp = spacy.load('en_web_core_lg')
# then add the pipeline stage
nlp.add_pipe('sentence_bert', config={'model_name': 'stsb-xlm-r-multilingual'})
```


Let me know if this works for you.

Best,
Martino

**Comment by Matthieu-Tinycoaching** [comment]
Hi @MartinoMensio thanks for the update I will test it as soon as possible.
