### ISSUE TITLE
Use in pipe?

### ISSUE THREAD

**Issue by duxan** [MartinoMensio/spacy-sentence-bert#2]
Hi, awesome library!

I have some problems though to run it in nlp.pipe - can you please clarify how that would go?

**Comment by MartinoMensio** [comment]
Hi @duxan ,
Thank you for opening your issue. What is the problem you are having? What are you trying to do?

I tried to use this model with `nlp.pipe` with the following snippet and I didn't see problems:

```python
import spacy

nlp = spacy.blank('en')
nlp.add_pipe('universal_sentence_encoder')

texts = ["One document.", "Another document", "Lots of documents"]
for doc in nlp.pipe(texts, batch_size=50):
    vector = doc.vector
    print(vector.shape)
```

**Comment by MartinoMensio** [comment]
Hi @duxan ,
Thank you for opening your issue. What is the problem you are having? What are you trying to do?

I tried to use this model with `nlp.pipe` with the following snippet and I didn't see problems:

```python
import spacy

nlp = spacy.blank('en')
nlp.add_pipe('sentence_bert', config={'model_name': 'en_stsb_bert_base'})

texts = ["One document.", "Another document", "Lots of documents"]
for doc in nlp.pipe(texts, batch_size=50):
    vector = doc.vector
    print(vector.shape)
```

**Comment by duxan** [comment]
Ah, the problem I had was that I used `n_process`  param, and vectors were empty. This example works as expected. Thanks a lot.

**Comment by MartinoMensio** [comment]
Yes, with n_processes there are some errors because the model unfortunately is not fork-safe.
