### ISSUE TITLE
Fine-tune bert model

### ISSUE THREAD

**Issue by eneszv** [MartinoMensio/spacy-sentence-bert#4]
Hi, 
Is there a way to fine-tune some of the provided models?
Could you please show a minimal working example?
Thanks

**Comment by MartinoMensio** [comment]
Hi @eneszv ,
Since this library is only a wrapper of sentence-transformers, I would suggest looking at the documentation of sentence-transformers for fine-tuning: https://www.sbert.net/docs/training/overview.html

Best,
Martino
